FROM ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.10.2}
USER airflow
RUN pip install apache-airflow-providers-airbyte[http] \
    && pip install apache-airflow-providers-airbyte \
    && pip install dbt-core dbt-snowflake
